### ISSUE TITLE
parse_contdotdat.py in ALMAIMF

### ISSUE THREAD

**Issue by AndresErnestoGuzman** [ALMA-IMF/reduction#127]
Hi Adam, 

I have a question on this script. Shouldn't this line be 
`if fmin < fhi < fmax or fmax > flo > fmin:`
?

https://github.com/ALMA-IMF/reduction/blob/dc4f80afdd4660d119636781e5c42e05600214db/reduction/parse_contdotdat.py#L64

Andres

**Comment by keflavich** [comment]
yes, fixed here: https://github.com/ALMA-IMF/reduction/commit/c8ac332be68d439d47b64525bd6a1101d73a3f89

I don't think this would have caused any issues, though, since in the case that `fhi < fmin` (which we would have caught incorrectly before), the following line:
https://github.com/ALMA-IMF/reduction/blob/dc4f80afdd4660d119636781e5c42e05600214db/reduction/parse_contdotdat.py#L65
would have resulted in `selected |= False`, i.e., no change.
